### ISSUE TITLE
Ubuntu21.10 ./build_linux.sh debug报错

### ISSUE THREAD

**Issue by hcp6897** [BoomingTech/Pilot#10]
$ ./build_linux.sh debug
-- Using X11 for window creation
-- Build spdlog: 1.9.2
-- Build type: Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /Pilot/build
************************************************************* 
**** [Precompile] BEGIN 
************************************************************* 
**/Pilot/engine/bin/Linux/meta_parser: error while loading shared libraries: libclang.so.12: cannot open shared object file: No such file or directory**
gmake[2]: *** [CMakeFiles/PilotPreCompile.dir/build.make:73: CMakeFiles/PilotPreCompile] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:261: CMakeFiles/PilotPreCompile.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by BoomingTech-YuqiaoZhang** [comment]
The [github workflow](https://github.com/BoomingTech-YuqiaoZhang/Pilot/actions/workflows/build_linux.yml) is passing.
We strongly recommend the Ubuntu LTS version for you. 
Perhaps the libc++ and clang are missing. You may use "apt install clang" and "apt install libc++" first.

**Comment by WANGSSSSSSS** [comment]
this problem is due to your wrong ld library path configuration, thus you can add the following line in `build_linux.sh` file
`export export LD_LIBRARY_PATH= xxxxxx/Pilot/engine/bin/Linux` , replace xxxxx with your codebase path
