### ISSUE TITLE
Update .gitignore file to ignore clion intermediate files

### ISSUE THREAD

**Issue by Wlain** [BoomingTech/Pilot#101]
->.gitignore
compiledDependencies/
cmake-build-*
build-*
.idea/

update gitignore configuration

**Comment by hyv1001** [comment]
Hi, @Wlain 
If you have a bug, please give a clear and concise description of what the bug is.
Or if you would like to update the `.gitignore` file, you could send a PR with the commit or submit a feature request issue.

**Comment by hyv1001** [comment]
Should be resolved by #103
