### ISSUE TITLE
Camera移动速度过慢

### ISSUE THREAD

**Issue by watermellye** [BoomingTech/Pilot#109]
在Editor中，摄像机在画面中（Editor mode）通过wasd移动的速度很缓慢，每次想移动到一个新的位置都要花费很多时间。
可以官方考虑加快移动速度吗？还是说推荐自己阅读和修改源码。

**Comment by hyv1001** [comment]
We would like to implement a mechanism to increase the movement speed of the camera by pressing the shift key.

**Comment by ShenMian** [comment]
你可以试试用 Release 条件编译的编辑器, 会快不少. 
我这感觉刚好, 所以不建议单纯的加快速度. 之后可以考虑到时间增量, 来确保不同环境下相机的移动速度相同.

**Comment by Ol6rin** [comment]
This issue has been solved by Pull Request #140.
此问题已被Pull Request #140 解决。
