### ISSUE TITLE
能帮忙解释一下source/_generated文件夹下的反射和序列化代码是如何自动生成的么？

### ISSUE THREAD

**Issue by huoyushequ** [BoomingTech/Pilot#113]
能帮忙解释一下source/_generated文件夹下的反射和序列化代码是如何自动生成的么？在cmake阶段的代码是如何实现的？

**Comment by huoyushequ** [comment]
找到了，是用的这个：\Pilot\engine\bin\Windows\x64\meta_parser.exe ， 不是开源的

**Comment by huoyushequ** [comment]
PS C:\Users\work\Pilot\engine\bin\Windows\x64> .\meta_parser.exe
Arguments parse error!
Please call the tool like this:
chaos_meta_parser.exe  project_file_name  include_file_name_to_generate  project_base_directory  module_name option[SI] showErrors(0 or 1) cmakeMode(cmake or other)
        -C(spcify input profile) ..(profile name) -D(cmake build type) ASAN/Check/Profile/Ship(select one type)

**Comment by huoyushequ** [comment]
是用的自研的元数据解析工具，自动生成了代码，只可惜不开源，没法学习了

**Comment by hyv1001** [comment]
后续有这方面的规划，会随着课程的进展逐步开放

**Comment by huoyushequ** [comment]
感谢您的回答
