### ISSUE TITLE
MacOS 高分屏视口大小位置不正确

### ISSUE THREAD

**Issue by yanjifa** [BoomingTech/Pilot#12]
这是我尝试修改的代码，在我的 Mac 上运行正常， 但是因为没有在其他平台测试，所以贴到这里，供参考

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/5621114/161584151-a453a0e0-3a87-4bd5-afc4-b364b24f5b68.png">

**Comment by AvatarGuo** [comment]
亲测有效 + 1

**Comment by SevenYears** [comment]
棒，MAC有效

**Comment by hyv1001** [comment]
Thx, this is a known issue, will be fixed soon

**Comment by hyv1001** [comment]
The issue should be fixed by #41

**Comment by X1ehua** [comment]
It works on the secondary 1080p monitor, but while the Xcode and PilotEditor running on the Retina display, the issue occurs again.
