### ISSUE TITLE
请问一下，关于添加压缩文件作为引擎文件系统的计划？

### ISSUE THREAD

**Issue by rocketman123456** [BoomingTech/Pilot#124]
关于这一点，为了提高文件加载速度，减少资源文件的空间占用，许多引擎会采取某种方式的压缩来作为资源文件的基石。作为一个开源引擎，我个人认为zip格式是一个很合适的文件类型。请问关于这方面的功能有没有相关的开发计划呢？如果没有，请问该如何针对这个部分设计相应的文件系统呢？

**Comment by hyv1001** [comment]
是的，现代引擎的资源管理必然是会支持压缩文件存储，Pilot后续也会继续开发相应的功能，只是相应一定的开发时间。
zip格式虽然压缩率还可以，但压缩及解压缩速度无法满足要求，游戏引擎中常用的算法是 [lz4](https://github.com/lz4/lz4)。

**Comment by rocketman123456** [comment]
请问有没有这个方面的设计的资料呢？我想在我fork的分支上开发一个试试看，但是不知道怎么样算是比较好又简洁的解决方案。参考书目里面的内容有点抽象，脑海中没办法对应到具体的系统上来。

**Comment by hyv1001** [comment]
这篇[blog](https://simoncoenen.com/blog/programming/PakFiles)中有一个简单的实现
商业引擎中的实现相对要复杂很对，如果想要学习的话，可以参考Unreal或者[o3de](https://github.com/o3de/o3de/tree/development/Code/Framework/AzFramework/AzFramework/Archive)中的相关代码

**Comment by rocketman123456** [comment]
> 这篇[blog](https://simoncoenen.com/blog/programming/PakFiles)中有一个简单的实现 商业引擎中的实现相对要复杂很多，如果想要学习的话，可以参考Unreal或者[o3de](https://github.com/o3de/o3de/tree/development/Code/Framework/AzFramework/AzFramework/Archive)中的相关代码

好的，谢谢

**Comment by hyv1001** [comment]
This issue will be closed, plz reopen or create a new ticket if you have any questions.
