### ISSUE TITLE
windows下build失败

### ISSUE THREAD

**Issue by IndifferentArea** [BoomingTech/Pilot#126]
**Describe the bug | Bug描述**
windows10下在VS2019中build时失败
- 试过cmake和运行.bat两种方法,后者会出现红色报错，二者输出结果相同
- build文件夹下文件比hw指导文档中截图展示得少得多
   
![FG8D$1GSV0Q9$F6}Z}8LOJ3](https://user-images.githubusercontent.com/74698401/163573225-e5fc5cde-4f5c-47a1-82f9-071eb7d9355c.png)

- sln方案构建时显示：完成生成项目“PilotRuntime.vcxproj”的操作 - 失败。

**Screenshots/Logs | 截图/日志**

![MB1`LF~CE3@%%P~MB2$ 8G](https://user-images.githubusercontent.com/74698401/163572590-4bcaf511-1275-4563-9762-e5ef936e657b.png)

**Comment by hyv1001** [comment]
请在命令行下执行以下命令： `build_windows.bat > build_log.txt`
然后把build_log.txt中的日志贴出来

![image](https://user-images.githubusercontent.com/102242553/163574921-5a8d8ead-d08a-4fa6-8f6b-4b4437295015.png)

**Comment by IndifferentArea** [comment]
[build_log.txt](https://github.com/BoomingTech/Pilot/files/8496117/build_log.txt)

如上

**Comment by hyv1001** [comment]
这可能是由于中文路径引发的，参考 #34 ，正式的修复方法正在开发中，临时方案可以通过移除中文路径解决。

**Comment by IndifferentArea** [comment]
已解决，谢谢！
![KT91XX`6TI65B0F)` STVO7](https://user-images.githubusercontent.com/74698401/163577654-393a220c-9611-42b0-ae9f-f5d77e8568e5.png)

Best wishes!

**Comment by cjj-1** [comment]
[](url)
[build_log.txt](https://github.com/BoomingTech/Piccolo/files/9682865/build_log.txt)
我这是为什么
