### ISSUE TITLE
请问关于meta parser的相关资料？

### ISSUE THREAD

**Issue by rocketman123456** [BoomingTech/Pilot#127]
关于生成代码部分，请问有没有对应的学习资料呢？

**Comment by hyv1001** [comment]
`meta parser` is a c++ reflection library implemented based on [libclang](https://clang.llvm.org/doxygen/group__CINDEX.html), you may find some resources from these links:
[Using Clang to generate C++ reflection data](https://www.reddit.com/r/gamedev/comments/3lh0ba/using_clang_to_generate_c_reflection_data/) 
[metareflect](https://github.com/leandros/metareflect)
And our code will be open-source soon.

There are also some other methods to implement c++ reflection, such as [rttr](https://github.com/rttrorg/rttr)

**Comment by hyv1001** [comment]
This issue will be closed, plz reopen or create a new ticket if you have any problems.
