### ISSUE TITLE
Windows 平台Pilot.sln工程调试运行失败：0x00007FF862F64F69 处(位于 PilotEditor.exe 中)有未经处理的异常: Microsoft C++ 异常: std::runtime_error，位于内存位置 0x000000E73EEFF030 处

### ISSUE THREAD

**Issue by JasonTheCoderMichael** [BoomingTech/Pilot#129]
打开Pilot.sln后F5调试运行工程，出现报错:
0x00007FF862F64F69 处(位于 PilotEditor.exe 中)有未经处理的异常: Microsoft C++ 异常: std::runtime_error，位于内存位置 0x000000E73EEFF030 处

![image](https://user-images.githubusercontent.com/13044798/163676651-f2272a6a-d3d0-49af-b429-3e03c690f583.png)

IDE是Visual Studio Community 2022。
CMake 版本： 3.23.1
Windows 10 SDK 10.0.19041.0

计算机硬件和系统情况如图:
![image](https://user-images.githubusercontent.com/13044798/163676611-0a401be1-c3b6-4f7d-bda6-9dcbfd42a18d.png)

**Comment by HuajiKojima** [comment]
初步看起来貌似是vulkan的实例创建失败，抛出了一个std异常，有没有试着排查一下vulkan SDK和gpu驱动程序支持vulkan版本之间的不兼容（可能性不大，但还是建议看一下）？

**Comment by hyv1001** [comment]
请提供一下GPU相关信息，比如：

- 是否多GPU
- GPU 1型号：
- GPU 2型号（如果有）：
- GPU 驱动版本：

**Comment by JasonTheCoderMichael** [comment]
> 

我截个图哈
![image](https://user-images.githubusercontent.com/13044798/163709085-55c5b329-1f09-4ca0-a146-a6da31010c83.png)
![image](https://user-images.githubusercontent.com/13044798/163709091-ffc1442f-e1a5-452d-abbf-29625bb6fe93.png)
![image](https://user-images.githubusercontent.com/13044798/163709098-030394d4-0b0e-41db-81d4-855271dacb32.png)

**Comment by JasonTheCoderMichael** [comment]
> 初步看起来貌似是vulkan的实例创建失败，抛出了一个std异常，有没有试着排查一下vulkan SDK和gpu驱动程序支持vulkan版本之间的不兼容（可能性不大，但还是建议看一下）？

刚才查了下显卡驱动的说明文档，只支持vulkan 1.0，是这个原因吗？
![image](https://user-images.githubusercontent.com/13044798/163709851-4d1a0b43-f733-4da4-bcbe-50b88ba18916.png)

**Comment by hyv1001** [comment]
建议先升级一下显卡驱动，17年的驱动太老了

**Comment by JasonTheCoderMichael** [comment]
> 建议先升级一下显卡驱动，17年的驱动太老了

收到 ，非常感谢啊
