### ISSUE TITLE
”无法启动程序，Pilot\build\x64\Debug\ALL_BUILD“拒绝访问

### ISSUE THREAD

**Issue by ZoneLai** [BoomingTech/Pilot#130]
Windows平台VS打开Pilot.sln编译完成后提示 **”无法启动程序，Pilot\build\x64\Debug\ALL_BUILD“拒绝访问**。
注：Pilot\build\engine\source\editor\Debug\PilotEditor.exe双击打开正常运行

**Comment by HuajiKojima** [comment]
pilot解决方案的默认启动项目是ALL_BUILD，你可以试着看一下它的项目属性，并不是“应用程序（exe）”，而是“实用工具”。想要解决的话只要在解决方案资源管理器内找到“PilotEditor”项目并右键设置为启动项目即可。

**Comment by ZoneLai** [comment]
谢谢，已解决

**Comment by HuajiKojima** [comment]
不用客气，毕竟当初也是在这里摔过跤的 ;)

**Comment by hyv1001** [comment]
This issue will be closed, plz reopen or create a new ticket if still exists
