### ISSUE TITLE
M1 Mac 编译成功后，PilotEditor 无法打开，显示 killed

### ISSUE THREAD

**Issue by cheft** [BoomingTech/Pilot#135]
**Describe the bug | Bug描述**
编译成功后，PilotEditor 无法打开，终端里显示 [1]    89090 killed     ./bin/PilotEditor

**Steps to reproduce | 如何复现**
1. 下载 Pilot 源码
2. 通过脚本进行编译：./build_macos.sh release  或 ./build_macos.sh debug   
3. 编译成功后运行： ./bin/PilotEditor

**Expected behavior | 预期行为**
程序可以正常打开
    
**Actual behavior | 实际行为**
程序被终止，无法打开

**Screenshots/Logs | 截图/日志**
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/1567209/163901184-81ee78eb-afea-45ad-9363-36b8820fc9e4.png">

**Desktop | 桌面环境**
 - OS macOS 
 - Version macos monterey 12.3 (21E230)
 - CPU Apple M1
 - GPU Apple M1 8 core gpu
 - Memory 16GB
 - Compiler AppleClang 13.0

**Comment by ingra14m** [comment]
我的M1也遇到了这个问题。执行完`cmake -S . -B build -G "Xcode"`之后，无论通过`./build_macos.sh release` 或 `./build_macos.sh debug`还是`cmake --build build --config Release`，最终执行bin目录下的`./PilotEditor`都会kill，报错信息为`[1]    51507 killed     ./PilotEditor`。
后来尝试在每一个命令前加入sudo，同样也是kill

- OS: Version macos monterey 12.3.1
- CPU Apple M1 Max
- GPU 32
- Memory 32GB
- Compiler Apple clang version 13.0.0
- XCode 13.1

**Comment by ingra14m** [comment]
terminal使用Rosetta打开就可以了
应用 - iterm2 - 显示简介 - 使用Rosetta打开

**Comment by cheft** [comment]
Rosetta 模式下编译和运行确实可以了，多谢。
