### ISSUE TITLE
运行时报错throw std::runtime_error("enumerate physical devices");

### ISSUE THREAD

**Issue by Grand-two** [BoomingTech/Pilot#14]
报错页面如下：
![error](https://user-images.githubusercontent.com/52741513/161585199-38e4acc1-dba4-4243-a667-9dc45be3dfd4.png)

查了一下问题可能与下列问题有关，因为我的电脑也是ROG的笔记本，AMD的集显和NV的独显：
[https://stackoverflow.com/questions/68109171/vkenumeratephysicaldevices-not-finding-all-gpus](url)

尝试在Vulkan Configurator中Disable掉了VK_LAYER_AMD_swichable_graphics和VK_LAYER_NV_optimus，可以正常运行了
![error2](https://user-images.githubusercontent.com/52741513/161585793-672c5a33-bac1-4784-b10c-15f87427f7cd.png)

但发现运行时引擎主要占用的是我的集显：
![error3](https://user-images.githubusercontent.com/52741513/161587001-f7e3f0d3-b17e-4f06-8d7c-7db109b5c9ee.png)

请问是否有更好的解决方法，以及如何设置才能使得引擎使用我的独显？感激不尽！

**Comment by Adven00** [comment]
要调用独显修改这里就行

https://github.com/BoomingTech/Pilot/blob/4574200cb6bc19f17d30230d57883118b6f807a0/engine/source/runtime/function/render/source/vulkan_manager/context/vulkan_context.cpp#L321-L333

我是这样改的
```cpp
// find one device that matches our requirement
// if no discrete GPU exists, use the last suitable one
std::vector<VkPhysicalDevice> physical_devices(physical_device_count);
vkEnumeratePhysicalDevices(_instance, &physical_device_count, physical_devices.data());

for (const auto& device : physical_devices)
{
    if (isDeviceSuitable(device))
    {
        _physical_device = device;
        VkPhysicalDeviceProperties physical_device_properties;
        vkGetPhysicalDeviceProperties(device, &physical_device_properties);
        if (physical_device_properties.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU)
        {
            break;
        }
    }
}
```

**Comment by ShenMian** [comment]
#29

**Comment by hyv1001** [comment]
The issue will be closed, you can reopen it or create a new ticket if it still exists on your machine
