### ISSUE TITLE
windows编译为啥需要pthread呀...

### ISSUE THREAD

**Issue by caelumable** [BoomingTech/Pilot#141]
直接运行build_windows.bat

没成功，翻了一下CMakeError.log 输出的内容

Determining if the include file pthread.h exists failed with the following output:
Change Dir: F:/c++project/Pilot/build/CMakeFiles/CMakeTmp

Run Build Command(s):F:/vs2019/MSBuild/Current/Bin/MSBuild.exe cmTC_4b50c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.0.461+g6ff56ef63c

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.20.27508.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_4b50c.dir\Debug\\" /Fd"cmTC_4b50c.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue F:\c++project\Pilot\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  CheckIncludeFile.c

  

F:\c++project\Pilot\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [F:\c++project\Pilot\build\CMakeFiles\CMakeTmp\cmTC_4b50c.vcxproj]

使用环境：
windows 10
cmake 3.23.1
vs2019

**Comment by hyv1001** [comment]
pthread的报错是没什么影响的，某些第三方库会检查是否存在pthread，但不影响编译流程。
能否把build_windows.bat报错的结果发一下？

**Comment by caelumable** [comment]
> 的

不好意思，我之前用的是visual studio2019编译的，后来用2022编译了一下就通过了。。。。就不纠结了，谢谢
