### ISSUE TITLE
Windows运行时validation layer: Validation Error: 

### ISSUE THREAD

**Issue by wuxingogo** [BoomingTech/Pilot#149]
![image](https://user-images.githubusercontent.com/8916803/165130643-4100078e-260d-490a-8c00-896233404805.png)
可以运行，试着修改了rendering.global.json中的"color_grading_map": "asset/texture/lut/color_grading_lut_02.jpg",
感觉没有效果
背后的控制台一直在输出
validation layer: Validation Error: [ VUID-vkCmdDraw-magFilter-04553 ] Object 0: handle = 0x8f5f070000000095, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xce045c0000000096, type = VK_OBJECT_TYPE_SAMPLER; Object 2: handle = 0xb097c90000000027, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x6b4ef9a3 | Descriptor set VkDescriptorSet 0x8f5f070000000095[] encountered the following validation error at vkCmdDraw time: Sampler (VkSampler 0xce045c0000000096[]) is set to use VK_FILTER_LINEAR with compareEnable is set to VK_TRUE, but image view's (VkImageView 0xb097c90000000027[]) format (VK_FORMAT_R32G32B32_SFLOAT) does not contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT in its format features. The Vulkan spec states: If a VkSampler created with magFilter or minFilter equal to VK_FILTER_LINEAR and compareEnable equal to VK_FALSE is used to sample a VkImageView as a result of this command, then the image view's format features must contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdDraw-magFilter-04553)

**Comment by hyv1001** [comment]
This should be fixed by #147 , plz check the latest code
