### ISSUE TITLE
validation layers requested, but not available!

### ISSUE THREAD

**Issue by kk9265** [BoomingTech/Pilot#165]
看上去情况跟 #129  问题类似，我刚好是反面，我原先是正常的，然后因为某些原因将gtx1660显卡驱动更新到了最新513版本，之后vkEnumerateInstanceLayerProperties只能取出1个layout了 VK_LAYER_NV_optimus，目前将
m_enable_validation_Layers手动置成false，希望能找到更好的方法解决这个问题~多谢了~

**Comment by hyv1001** [comment]
1. 麻烦提供一下系统信息：
    * OS : 
    * 是否多GPU : 
    * GPU1 : 
    * GPU2(如果有) : 
2. 能否运行一下vulkan sdk下的vulkaninfoSDK.exe，并把输出dump出来，作为附件提交上来
![image](https://user-images.githubusercontent.com/102242553/166149861-7d76cb91-101b-4adb-a348-e2053dfda02f.png)

**Comment by kk9265** [comment]
多谢回复，我发现我的情况还蛮神奇的，我自己并没有主动装vulkan sdk，但是我之前确实是正常可以启动的，且没有安装vulkan sdk（神奇的地方，理论上应该一开始就不行才对呀，但是我有装虚幻引擎），本人台式机，只有一张显卡，window 10。
之前觉得是显卡驱动更新的问题，现在看有2种可能：
1.新的驱动导致
2.虚幻引擎升级至5.01导致
当然，我最后安装了vulkan sdk1.3 版之后就好了~考虑到环境并不是核心问题，现在已经可以正常取到validation layer，所以我打算close了。
再次感谢您的回复~

**Comment by hyv1001** [comment]
之前能运行的原因可能是由于引擎第三方库中包含了一个vulkansdk，但可能驱动升级后导致了不兼容，这个我们后续还会查一下
