### ISSUE TITLE
Raspberry Pi 4B Ubuntu 22.04 Compile Error 

### ISSUE THREAD

**Issue by rocketman123456** [BoomingTech/Pilot#167]
After install all required packages, i run build_linux.sh buid command, and i got error message:
```
/bin/sh: 1: /home/raspberry/Program/CppCode/Pilot/engine/3rdparty/VulkanSDK/bin/Linux/glslangValidator: Exec format error
/bin/sh: 1: /home/raspberry/Program/CppCode/Pilot/engine/3rdparty/VulkanSDK/bin/Linux/glslangValidator: Exec format error

gmake[2]: *** [engine/shader/CMakeFiles/PilotShaderCompile.dir/build.make:208: ../engine/shader/generated/spv/axis.vert.spv] Error 126
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [engine/shader/CMakeFiles/PilotShaderCompile.dir/build.make:212: ../engine/shader/generated/spv/color_grading.frag.spv] Error 126
```
May be it's an error about running vulkan glslangValidator on ubuntu 22.04 ?

**Comment by hyv1001** [comment]
It seems that this `glslangValidator` can not run at this machine.
You could try to install the sdk from [official website](https://vulkan.lunarg.com/doc/view/latest/linux/getting_started_ubuntu.html)

**Comment by rocketman123456** [comment]
Actually, for Raspberry Pi 4B, [this link](https://qengineering.eu/install-vulkan-on-raspberry-pi.html) may be the valid way to install Vulkan. Supported extensions are listed [here](https://mesamatrix.net/), many extensions are not supported. From [this link](https://www.khronos.org/conformance/adopters/conformant-products/vulkan#submission_596), may be Raspberry Pi 4B and Raspberry Pi CM4 are the only models that support Vulkan Driver. May be I should consider use another machine to run this engine instead of Raspberry Pi.

**Comment by rocketman123456** [comment]
And maybe we could update the build script to support more system. I hope this Pilot engine could run on more platforms such as android and iphone and other mobile device.
