### ISSUE TITLE
 请问为什么没有采用xmake作为cmake的代替呢？

### ISSUE THREAD

**Issue by rocketman123456** [BoomingTech/Pilot#188]
请问为什么没有采用xmake作为cmake的代替呢？两者相比各有什么优缺点呢？

**Comment by hyv1001** [comment]
网络上已经有很多cmake和xmake的对比，这里就不在赘述了。
选择cmake的原因主要是cmake在当前c++构建体系中基本占据了统治地位，绝大多数的c++开源软件都支持cmake构建，越来越多的IDE也支持了cmake文件作为工程构建文件，这也意味着存在大量会使用cmake以及会编写cmake文件的开发者，从而引擎构建相关的学习成本也会更低，这对一个新的开源项目来说至关重要。
