### ISSUE TITLE
关于多线程支持与添加新的功能模块？

### ISSUE THREAD

**Issue by rocketman123456** [BoomingTech/Pilot#197]
请问引擎会不会有多线程支持呢？还有就是有没有对于这个方面的比较好的资料？
最后是关于如何设计添加新的子系统呢？参考游戏引擎架构书，自己设计的小的子系统部分总觉得和这个引擎的其他代码风格不符合，希望能够提供更好的思路。

**Comment by hyv1001** [comment]
引擎会支持多线程，初步会实现Logic Thread 和 Rendering Thread, IO Thread的分离，最终会实现一套Job System来更管理和调度多线程tasks。
GDC上有不少引擎多线程的相关资料，这个[repo](https://github.com/SergeyMakeev/TaskScheduler)下有一些链接可以参考。

**Comment by rocketman123456** [comment]
谢谢🙏
