### ISSUE TITLE
meta_parser: Permission denied

### ISSUE THREAD

**Issue by syguan96** [BoomingTech/Pilot#2]
```
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using X11 for window creation
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Build spdlog: 1.9.2
-- Build type: Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/syguan/Pilot/build
************************************************************* 
**** [Precompile] BEGIN 
************************************************************* 
make[2]: execvp: /data/Pilot/engine/bin/Linux/meta_parser: Permission denied
make[2]: *** [CMakeFiles/PilotPreCompile.dir/build.make:73: CMakeFiles/PilotPreCompile] Error 127
make[1]: *** [CMakeFiles/Makefile2:261: CMakeFiles/PilotPreCompile.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

System: Ubuntu 20.04
Cmake: 3.23.0

**Comment by liangsen-zju** [comment]
System: Mac (Inter i7) Xcode 13.2.1

************************************************************* 
**** [Precompile] BEGIN 
************************************************************* 
/Users/lsen/CODE/Pilot/build/Pilot.build/Debug/PilotPreCompile.build/Script-C39BA26D421D57100E3E1526.sh: line 8: /Users/lsen/CODE/Pilot/engine/bin/macOS/meta_parser: Permission denied
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by begoss** [comment]
I also have this problem:

************************************************************* 
**** [Precompile] BEGIN 
************************************************************* 
/Users/huhao/GAMES104/PilotEngine/Pilot/build/Pilot.build/Debug/PilotPreCompile.build/Script-14BDE26028B03369204AA110.sh: line 8: /Users/huhao/GAMES104/PilotEngine/Pilot/engine/bin/macOS/meta_parser: Permission denied
Command PhaseScriptExecution failed with a nonzero exit code


System Version: MacOS Monterey 12.2.1, Apple M1 Max
Xcode Version: 13.2.1

**Comment by Duality142857** [comment]
I also have this problem on Ubuntu 18.04,  and I used sudo ./build_linux.sh                
-- Using X11 for window creation
-- Build spdlog: 1.9.2
-- Build type: Release
-- Configuring done
-- Generating done
-- Build files have been written to: /home/number/approot/engines/Pilot/build
************************************************************* 
**** [Precompile] BEGIN 
************************************************************* 
make[2]: execvp: /home/number/approot/engines/Pilot/engine/bin/Linux/meta_parser: Permission denied
CMakeFiles/PilotPreCompile.dir/build.make:70: recipe for target 'CMakeFiles/PilotPreCompile' failed
make[2]: *** [CMakeFiles/PilotPreCompile] Error 127
CMakeFiles/Makefile2:260: recipe for target 'CMakeFiles/PilotPreCompile.dir/all' failed
make[1]: *** [CMakeFiles/PilotPreCompile.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Yescafe** [comment]
Use `chmod` command to add `executable` permission.

```shell
chmod +x engine/bin/macOS/meta_parser
```

**Comment by BoomingTech-YuqiaoZhang** [comment]
we are fixing now!

**Comment by BoomingTech-YuqiaoZhang** [comment]
You can use the following commands to fix the build error on Linux temporarily. A merge request will be provided later
chmod +x build_linux.sh
chmod +x "./engine/bin/Linux/meta_parse"
chrpath -r '$ORIGIN' "./engine/bin/Linux/meta_parser"
chmod +x "engine/3rdparty/VulkanSDK/bin/Linux/glslangValidator"

**Comment by BoomingTech-YuqiaoZhang** [comment]
If you are hasty, you may use  [this repository](https://github.com/BoomingTech-YuqiaoZhang/Pilot) instead

**Comment by Duality142857** [comment]
> You can use the following commands to fix the build error on Linux temporarily. A merge request will be provided later chmod +x build_linux.sh chmod +x "./engine/bin/Linux/meta_parse" chrpath -r '$ORIGIN' "./engine/bin/Linux/meta_parser" chmod +x "engine/3rdparty/VulkanSDK/bin/Linux/glslangValidator"

Now it gives this error:

meta_parser: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
CMakeFiles/PilotPreCompile.dir/build.make:70: recipe for target 'CMakeFiles/PilotPreCompile' failed
make[2]: *** [CMakeFiles/PilotPreCompile] Error 127
CMakeFiles/Makefile2:260: recipe for target 'CMakeFiles/PilotPreCompile.dir/all' failed
make[1]: *** [CMakeFiles/PilotPreCompile.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bolin12** [comment]
> You can use the following commands to fix the build error on Linux temporarily. A merge request will be provided later chmod +x build_linux.sh chmod +x "./engine/bin/Linux/meta_parse" chrpath -r '$ORIGIN' "./engine/bin/Linux/meta_parser" chmod +x "engine/3rdparty/VulkanSDK/bin/Linux/glslangValidator"

not work for me

**Comment by BoomingTech-YuqiaoZhang** [comment]
You can use the following commands to fix the build error on MacOS temporarily
chmod +x "./engine/bin/MacOS/meta_parse"
export LD_LIBRARY_PATH=./engine/bin/macOS${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

**Comment by BoomingTech-YuqiaoZhang** [comment]
> > You can use the following commands to fix the build error on Linux temporarily. A merge request will be provided later chmod +x build_linux.sh chmod +x "./engine/bin/Linux/meta_parse" chrpath -r '$ORIGIN' "./engine/bin/Linux/meta_parser" chmod +x "engine/3rdparty/VulkanSDK/bin/Linux/glslangValidator"
> 
> not work for me

If you are hasty, you may use [this repository](https://github.com/BoomingTech-YuqiaoZhang/Pilot) instead. The github workflows are added.

**Comment by bolin12** [comment]
> > > You can use the following commands to fix the build error on Linux temporarily. A merge request will be provided later chmod +x build_linux.sh chmod +x "./engine/bin/Linux/meta_parse" chrpath -r '$ORIGIN' "./engine/bin/Linux/meta_parser" chmod +x "engine/3rdparty/VulkanSDK/bin/Linux/glslangValidator"
> > 
> > 
> > not work for me
> 
> If you are hasty, you may use [this repository](https://github.com/BoomingTech-YuqiaoZhang/Pilot) instead. The github workflows are added.

thx, this repo works fine
