### ISSUE TITLE
引擎退出后，物理系统析构时报错

### ISSUE THREAD

**Issue by Morcki** [BoomingTech/Pilot#202]
https://github.com/BoomingTech/Pilot/blob/882b377f8d6dba2378201c2187d5f1d1aacaff82/engine/source/runtime/function/physics/physics_system.cpp#L70-L78
# Bug：
![1FB@ MDM_7BXNSRTK%948YS](https://user-images.githubusercontent.com/34432001/169766875-7f9d5b5f-a418-45db-9afb-8a698eb15683.png)

# 分析：
https://github.com/BoomingTech/Pilot/blob/4b5b9629a2af3957d15040ddd357ffcaaa04dd95/engine/source/runtime/function/global/global_context.cpp#L55-L77

系统析构顺序如上，m_physics_system先于m_world_manager析构。
在m_world_manager析构时，其level_pair下属的m_gobjects依次析构，而gobject派生类RigidBodyComponent的析构调用了物理系统m_physics_system的removePhyicsActor函数（见下方），而此时m_physics_system已经析构。

https://github.com/BoomingTech/Pilot/blob/4b5b9629a2af3957d15040ddd357ffcaaa04dd95/engine/source/runtime/function/framework/component/rigidbody/rigidbody_component.cpp#L27-L34

**Comment by hyv1001** [comment]
感谢上报BUG。
这个问题在最新版本里面已经修复了 #203
