### ISSUE TITLE
VS 2019 Debug 模式报错 Release正常

### ISSUE THREAD

**Issue by dingyalei** [BoomingTech/Pilot#22]
![image](https://user-images.githubusercontent.com/35106422/161714458-18a885dc-f250-4643-9ff5-09d8f37d8d5d.png)

win10 SDK版本： 10.0.19041.0
操作系统 win10 专业版

**Comment by XuDaFei** [comment]
已经收到你的消息徐飞

**Comment by dingyalei** [comment]
已解决
