### ISSUE TITLE
Transform in Component Details panel is broken

### ISSUE THREAD

**Issue by yangkeshengli** [BoomingTech/Pilot#227]
**Describe the bug | Bug描述**
when change the transform of a object in scene, such as position, change position value  but the object not move,
but  the axis of object moved. pleasefix

**Steps to reproduce | 如何复现**
1. chose a object, an change the value of right transform.
2.  then you will see.

**Comment by Ol6rin** [comment]
Thank you for your feedback! We have noticed the bug, it will be fixed in future releases.
