### ISSUE TITLE
hw3 分支 build 失败

### ISSUE THREAD

**Issue by snow-orld** [BoomingTech/Pilot#241]
切换到games104/homework03-animation-physics分支后，使用 `sh build_macos.sh release` build失败。 

**Desktop | 桌面环境**
 - OS: macOS Monterey
 - CPU: Intel
 - GPU: Radeon Pro 560X 4 GB
 - Memory: 16GB

[compile.log](https://github.com/BoomingTech/Pilot/files/8824114/compile.log)

**Comment by hyv1001** [comment]
Should be fixed by #243
