### ISSUE TITLE
窗口最大化时Crash

### ISSUE THREAD

**Issue by Morcki** [BoomingTech/Pilot#244]
**Bug描述**
1. 当点击最大化引擎窗口界面时，代码在如下地方Crash。
![image](https://user-images.githubusercontent.com/34432001/171995682-042e76ae-0bdb-4995-807d-6e42c7f1c2e8.png)
2. 对应的代码为：
https://github.com/BoomingTech/Pilot/blob/238984e07efca2ceb8ecb0c78c80d91a2ad0ce21/engine/source/runtime/function/render/rhi/vulkan/vulkan_rhi.cpp#L212-L232

**Bug分析**
![image](https://user-images.githubusercontent.com/34432001/171995985-aebfeb62-27f8-4e87-a6c1-f503a8f65a90.png)

上图中，m_is_frame_in_flight_fences[m_current_frame_index]存储的VkFence*地址对应的内存都是问号，应该是m_is_frame_in_flight_fences出了问题，但我对vulkan不太熟悉，不知道怎么做进一步分析。

**Comment by hyv1001** [comment]
麻烦提供一下操作系统版本以及GPU型号，显存大小

**Comment by Morcki** [comment]
> 麻烦提供一下操作系统版本以及GPU型号，显存大小

感谢提醒，应该是显卡出了问题，解决方案是更新显卡驱动。

我查了一下我的显卡，发现GeForce这个图标提示不能work，然后我更新显卡驱动并重新安装显卡驱动之后，就能正常缩放窗口了。
![image](https://user-images.githubusercontent.com/34432001/172575410-c58ac6a3-330a-4484-b649-de69dfdd5922.png)
