### ISSUE TITLE
Pilot crashed after reload current level

### ISSUE THREAD

**Issue by ccqil** [BoomingTech/Pilot#3]
If we click Reload Current Level button and then run the editor, pilot will crash.
![图片](https://user-images.githubusercontent.com/24586659/161560924-c007b1e4-41f0-4e66-a985-ac0de84475f7.png)
It seems like that some codes from  `editor.cpp` is wrong:
```C++
        if (ImGui::BeginMenuBar())
        {
            if (ImGui::BeginMenu("Menu"))
            {
                if (ImGui::MenuItem("Reload Current Level"))
                {
                    WorldManager::getInstance().reloadCurrentLevel();
                    onGObjectSelected(PILOT_INVALID_GOBJECT_ID);
                }
                if (ImGui::MenuItem("Save Current Level"))
                {
                    WorldManager::getInstance().saveCurrentLevel();
                }
                if (ImGui::MenuItem("Exit"))
                {
                    exit(0);
                }
                ImGui::EndMenu();
            }
            ImGui::EndMenuBar();
        }
```
the line 343 should not be
```C++
onGObjectSelected(PILOT_INVALID_GOBJECT_ID);
```

**Comment by ShenMian** [comment]
https://github.com/BoomingTech/Pilot/blob/4574200cb6bc19f17d30230d57883118b6f807a0/engine/source/editor/source/editor_ui.cpp#L256-L263

**Comment by hyv1001** [comment]
@Ol6rin please check this issue

**Comment by Ol6rin** [comment]
Thank you very much for your feedback! The crash is related to unproperly handled PhysicsActors. We're working on the patch code now. It will be released in the next update after passing the test.
