### ISSUE TITLE
windows下生成的exe闪退，在vs下运行有报错，内存越界

### ISSUE THREAD

**Issue by for-heart-peace** [BoomingTech/Pilot#32]
m_vulkan_api_version = VK_API_VERSION_1_0; 这行代码报0x00007FFB914C4F69 处(位于 PilotEditor.exe 中)有未经处理的异常: Microsoft C++ 异常: std::runtime_error，位于内存位置 0x0000009FAC16F398 处。

调用堆栈为KernelBase.dll

**Comment by for-heart-peace** [comment]
AMD的集显和nv的独显，禁用了AMD的集显后，可以运行了

**Comment by hyv1001** [comment]
This issue should be fixed at the latest code, it will pick the dedicated GPU firstly, please check the MR: #29

**Comment by 772148702** [comment]
双屏还是会出现这个问题
