### ISSUE TITLE
Windows上编译失败

### ISSUE THREAD

**Issue by rayz-bee** [BoomingTech/Pilot#33]
cmake版本：3.23.0
g++版本：11.2.0(Rev10, Built by MSYS2 project) 
1. 先运行`cmake -S engine/ -B build -G "MinGW Makefiles"`，
2. 然后运行` cmake --build build --config Release`
3. 中间出现很多`ERROR: Failed to open file: C:/Users/Ray/Documents/Pilot/engine/shader/generated/spv/xxxxxx.frag.spv`
4. 以及：
`In file included from C:/Users/Ray/Documents/Pilot/engine/source/_generated/reflection/all_reflection.h:7,
                 from C:\Users\Ray\Documents\Pilot\engine\source\runtime\core\meta\reflection\reflection_register.cpp:8:C:/Users/Ray/Documents/Pilot/engine/source/_generated/reflection/animation_clip.reflection.gen.h: In static member function 'static void Pilot::Reflection::TypeFieldReflectionOparator::TypeAnimNodeMapOperator::set_convert(void*, void*)':
C:/Users/Ray/Documents/Pilot/engine/source/_generated/reflection/animation_clip.reflection.gen.h:29:145: error: no match for 'operator=' (operand types are 'std::vector<std::__cxx11::basic_string<char> >' and 'int')
   29 |        static void set_convert(void* instance, void* field_value){ static_cast<AnimNodeMap*>(instance)->convert = *static_cast<int*>(field_value);}`

**Comment by rayz-bee** [comment]
去WSL Linux上编译通过了，第三方库产生了805个warnings，吓死以为又要失败了

**Comment by rayz-bee** [comment]
Linux上编译通过

**Comment by miman-booming** [comment]
> cmake版本：3.23.0 g++版本：11.2.0(Rev10, Built by MSYS2 project)
> 
> 1. 先运行`cmake -S engine/ -B build -G "MinGW Makefiles"`，
> 2. 然后运行` cmake --build build --config Release`
> 3. 中间出现很多`ERROR: Failed to open file: C:/Users/Ray/Documents/Pilot/engine/shader/generated/spv/xxxxxx.frag.spv`
> 4. 以及：
>    `In file included from C:/Users/Ray/Documents/Pilot/engine/source/_generated/reflection/all_reflection.h:7, from C:\Users\Ray\Documents\Pilot\engine\source\runtime\core\meta\reflection\reflection_register.cpp:8:C:/Users/Ray/Documents/Pilot/engine/source/_generated/reflection/animation_clip.reflection.gen.h: In static member function 'static void Pilot::Reflection::TypeFieldReflectionOparator::TypeAnimNodeMapOperator::set_convert(void*, void*)': C:/Users/Ray/Documents/Pilot/engine/source/_generated/reflection/animation_clip.reflection.gen.h:29:145: error: no match for 'operator=' (operand types are 'std::vector<std::__cxx11::basic_string<char> >' and 'int') 29 |        static void set_convert(void* instance, void* field_value){ static_cast<AnimNodeMap*>(instance)->convert = *static_cast<int*>(field_value);}`

你可以检查下engine/shader/generated/下spv文件夹是不是不存在？如果不存在的话，可以手动创建spv文件夹，应该可以解决该问题。

**Comment by hyv1001** [comment]
Should be fixed by #102 , please reopen if still exists

**Comment by rayz-bee** [comment]
在Visual Studio里下载了全套Windows SDK以后编译没问题了。
