### ISSUE TITLE
无法在视口中点击鼠标左键选中物体

### ISSUE THREAD

**Issue by EoralMilk** [BoomingTech/Pilot#42]
无法在视口中点击鼠标左键选中物体
右侧物体列表中可以正常选中物体

**Comment by EoralMilk** [comment]
windows10， 使用vs2019 build release与直接启动build_windows.bat生成的exe都有这个问题。

**Comment by EoralMilk** [comment]
完全不能选中，试了很多次了，没有成功过。
在右侧列表中选中物体后点击视口倒是可以取消选择。 @hyv1001

**Comment by EoralMilk** [comment]
同时game mode下，鼠标被隐藏时仍能点击到编辑器的ui元素

**Comment by hyv1001** [comment]
Could you provide the build environment, such as：

- OS:
- CPU:
- GPU:
- Memory:

**Comment by EoralMilk** [comment]
![pilottest-bug-fullsize](https://user-images.githubusercontent.com/33147245/161966483-3bdb946e-5daa-4dcd-b59f-cfa056c333fe.gif)

**Comment by EoralMilk** [comment]
![QQ截图20220406194041](https://user-images.githubusercontent.com/33147245/161967423-37906d35-41df-4c16-8c2c-11e54c82bed4.png)
![QQ截图20220406194330](https://user-images.githubusercontent.com/33147245/161967426-880d4c2d-cfca-4c43-8346-7dad84ccc223.png)

**Comment by ShenMian** [comment]
请问你单击视口中有物体的地方时, 终端(控制台)有输出带 "no game object selected" 字样的内容吗?

**Comment by EoralMilk** [comment]
有输出 @ShenMian

**Comment by EoralMilk** [comment]
![pilottest-bug-fullsize2](https://user-images.githubusercontent.com/33147245/161997544-7bf6d2e8-ad9e-457e-942a-5ea857a1af16.gif)
@hyv1001

**Comment by EoralMilk** [comment]
![pilottest-bug-fullsize2](https://user-images.githubusercontent.com/33147245/161997636-81afc985-f61a-48bb-a2b5-1106faac3c2f.gif)

**Comment by EoralMilk** [comment]
> 那么问题可能就出在下面三行之中:
> 
> https://github.com/BoomingTech/Pilot/blob/8780ad0b2b8e3d5fcd19516216fe8e62d4fecf35/engine/source/editor/source/editor_ui.cpp#L960-L963
> 
> 
> 如果 `picked_uv` 的值是正确的, 问题就可能出在 `PPickPass::pick` 中.

好的，等我有时间看看。
我还想问一下，game mode下隐藏鼠标后仍能选中ui元素是我这里出bug了还是暂时没做处理。

**Comment by ShenMian** [comment]
@EoralMilk 隐藏鼠标的实现方法如下:
https://github.com/BoomingTech/Pilot/blob/529a140a23931addf593b14cf19cfc051e7e5d0d/engine/source/runtime/function/render/source/surface.cpp#L19
据我所知, 这个函数在某些情况下并不能完全正常工作(我不太清楚原因和解决方案). 而且如果鼠标移动过快的话, 是可能在被移动回窗口中心时移动到UI组件上的.
你遇到的情况是不是即使没有快速甩动鼠标, 但还是会触发UI组件的反应? 如果是, 应该就是第一种情况了.

**Comment by EoralMilk** [comment]
> @EoralMilk 隐藏鼠标的实现方法如下:
> 
> https://github.com/BoomingTech/Pilot/blob/529a140a23931addf593b14cf19cfc051e7e5d0d/engine/source/runtime/function/render/source/surface.cpp#L19
> 
> 
> 据我所知, 这个函数在某些情况下并不能完全正常工作(我不太清楚原因和解决方案). 而且如果鼠标移动过快的话, 是可能在被移动回窗口中心时移动到UI组件上的.
> 你遇到的情况是不是即使没有快速甩动鼠标, 但还是会触发UI组件的反应? 如果是, 应该就是第一种情况了.



> ![pilottest-bug-fullsize](https://user-images.githubusercontent.com/33147245/161966483-3bdb946e-5daa-4dcd-b59f-cfa056c333fe.gif)

嗯，我上传了gif里展示了，没有快速甩鼠标，它很稳定的不正常工作。 = =

**Comment by ShenMian** [comment]
@EoralMilk 对不起, 我要更正一点: glfw 的实现并不会将光标拉回窗口中心. 你目前遇到的现象是正常的.

**Comment by kwbm** [comment]
According to my research, I found that Intel's integrated graphics card driver behaves abnormally when copy tiling images

**Comment by kwbm** [comment]
https://stackoverflow.com/questions/37214140/does-vkcmdcopyimagetobuffer-work-when-source-image-uses-vk-image-tiling-optimal

**Comment by Morcki** [comment]
我在vs2017，win10的环境下也遇到了这个问题。
目前我的解决办法是注释掉copy_to_buffer_barrier的ImageMemoryBarrier流程，然后就能正常选中目标物体了。
```
        //VkImageMemoryBarrier copy_to_buffer_barrier {};
        //copy_to_buffer_barrier.sType               = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
        //copy_to_buffer_barrier.pNext               = nullptr;
        //copy_to_buffer_barrier.srcAccessMask       = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
        //copy_to_buffer_barrier.dstAccessMask       = VK_ACCESS_TRANSFER_READ_BIT;
        //copy_to_buffer_barrier.oldLayout           = VK_IMAGE_LAYOUT_UNDEFINED;
        //copy_to_buffer_barrier.newLayout           = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
        //copy_to_buffer_barrier.srcQueueFamilyIndex = m_p_vulkan_context->_queue_indices.graphicsFamily.value();
        //copy_to_buffer_barrier.dstQueueFamilyIndex = m_p_vulkan_context->_queue_indices.graphicsFamily.value();
        //copy_to_buffer_barrier.image               = _framebuffer.attachments[0].image;
        //copy_to_buffer_barrier.subresourceRange    = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
```
事实上，我也尝试将`copy_to_buffer_barrier.oldLayout`改为`VK_IMAGE_LAYOUT_PREINITIALIZED`和`VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL`，也能正常选中物体，但是vulkan会报错：
```
validation layer: Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x2366c3e80f0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x2366c3e80f0[] expects VkImage 0xbd60bd0000000076[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL.
```
抱歉我之前没有接触过vulkan，对`VkImageMemoryBarrier`和`VkImageLayout`了解不深，希望能搞清楚这里发生的情况。
