### ISSUE TITLE
Crashed At The Start On MacOS

### ISSUE THREAD

**Issue by begoss** [BoomingTech/Pilot#5]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/9478221/161564435-1be31917-6778-4948-8534-dc74bf92580e.png">

System Version: MaOS Monterey 12.2.1, Apple M1 Max
Xcode Version: 13.2.1

**Comment by syguan96** [comment]
See readme. M1 is not supported now.

**Comment by begoss** [comment]
Thx.

**Comment by zackszhu** [comment]
I actually succeeded in running the editor on M1 MacBook. Instead of using Xcode, I used ninja to build the project.

```
cmake -Sengine/ -Bbuild -GNinja
ninja -C build
```

Hope that helps.

**Comment by KaygNas** [comment]
> I actually succeeded in running the editor on M1 MacBook. Instead of using Xcode, I used [ninja](https://ninja-build.org) to build the project.
> 
> ```
> cmake -Sengine/ -Bbuild -GNinja
> ninja -C build
> ```
> 
> Hope that helps.

It do help, the editor built with ninja successfully runs on my MacBook Air M2.
