### ISSUE TITLE
where is the meta_parser on macOS?

### ISSUE THREAD

**Issue by jinjiankla** [BoomingTech/Pilot#64]
![截屏2022-04-07 下午4 05 45](https://user-images.githubusercontent.com/6223345/162151322-b2cd079f-47e5-4167-9550-f72698067e47.png)

**Comment by BoomingTech-YuqiaoZhang** [comment]
Hi. The "meta_parser" should be [here](https://github.com/BoomingTech/Pilot/blob/main/engine/bin/macOS/meta_parser)!

**Comment by hyv1001** [comment]
This issue will be closed, please reopen if you have any questions.
