### ISSUE TITLE
编辑器文件内容面板实现可以进行优化

### ISSUE THREAD

**Issue by ShenMian** [BoomingTech/Pilot#67]
问题:
对 Release 下构建的编辑器进行了简单的性能分析, **IO 占用了近 40% 的 CPU 时间**.
其中 `EditorUI::showEditorFileContentWindow()` 的占用率最为突出, 该函数每次调用都会创建一个新的 `EditorFileService` 实例, 然后调用 `EditorFileService::buildEngineFileTree()`. 在渲染目录后该类便被销毁.
在假设资源面板处于打开状态的时候, 每一帧都枚举了一遍资源文件夹及其子文件夹下的全部文件的信息.

个人觉得可行的方法:
将 `EditorFileService` 作为一个成员变量, 将目录结构**缓存**起来. 在指定时长后 或用户进行了资源导出等文件操作时刷新.

**Comment by hyv1001** [comment]
Good idea, however, we have no plan to make any serious optimization for Pilot currently, except it's a blocking issue. 
It's not necessary to update the file tree for each frame, it can be updated per second or after some operations as you said.
We'd appreciate it if you submit a PR about the optimization.

**Comment by hyv1001** [comment]
This issue has been resolved by #74
