### ISSUE TITLE
deepin 编译报错

### ISSUE THREAD

**Issue by windyslove** [BoomingTech/Pilot#68]
windys-dde@windys-dde-PC:/media/windys-dde/DATA/WorkSpaceDemo/Pilot$ ./build_linux.sh debug
-- Using X11 for window creation
-- Build spdlog: 1.9.2
-- Build type: Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /media/windys-dde/DATA/WorkSpaceDemo/Pilot/build
Consolidate compiler generated dependencies of target tinyobjloader
Consolidate compiler generated dependencies of target glm_static
Consolidate compiler generated dependencies of target json11
************************************************************* 
**** [Precompile] BEGIN 
************************************************************* 
[  0%] Built target stb
Consolidate compiler generated dependencies of target spdlog
[  1%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh.vert.spv
[  2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_directional_light_shadow.vert.spv
[  2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_inefficient_pick.vert.spv
[  2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_point_light_shadow.vert.spv
/media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/meta_parser: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/libclang.so.12)
make[2]: *** [CMakeFiles/PilotPreCompile.dir/build.make:73：CMakeFiles/PilotPreCompile] 错误 1
make[1]: *** [CMakeFiles/Makefile2:261：CMakeFiles/PilotPreCompile.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
Consolidate compiler generated dependencies of target glfw
/media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh.vert
/media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_directional_light_shadow.vert
[  3%] Built target json11
/media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_point_light_shadow.vert
/media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_inefficient_pick.vert
[  5%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_vert.h
[  6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_point_light_shadow_vert.h                                                                                              
[  6%] Built target tinyobjloader
[  6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_directional_light_shadow_vert.h                                                                                        
[  6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_inefficient_pick_vert.h
[  7%] Built target glm_static
[ 26%] Built target PilotShaderCompile
[ 38%] Built target glfw
[ 43%] Built target spdlog
make: *** [Makefile:136：all] 错误 2
windys-dde@windys-dde-PC:/media/windys-dde/DATA/WorkSpaceDemo/Pilot$ 

是因为系统的c库版本低了吗，当前系统搜索不到更高版本的c库了
deepin 20.5

**Comment by YuqiaoZhang** [comment]
Only Ubuntu is official supported.

**Comment by YuqiaoZhang** [comment]
/media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/meta_parser: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/libclang.so.12

> windys-dde@windys-dde-PC:/media/windys-dde/DATA/WorkSpaceDemo/Pilot$ ./build_linux.sh debug -- Using X11 for window creation -- Build spdlog: 1.9.2 -- Build type: Debug -- Configuring done -- Generating done -- Build files have been written to: /media/windys-dde/DATA/WorkSpaceDemo/Pilot/build Consolidate compiler generated dependencies of target tinyobjloader Consolidate compiler generated dependencies of target glm_static Consolidate compiler generated dependencies of target json11
> 
> **** [Precompile] BEGIN
> 
> [ 0%] Built target stb Consolidate compiler generated dependencies of target spdlog [ 1%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh.vert.spv [ 2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_directional_light_shadow.vert.spv [ 2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_inefficient_pick.vert.spv [ 2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_point_light_shadow.vert.spv /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/meta_parser: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/libclang.so.12) make[2]: *** [CMakeFiles/PilotPreCompile.dir/build.make:73：CMakeFiles/PilotPreCompile] 错误 1 make[1]: *** [CMakeFiles/Makefile2:261：CMakeFiles/PilotPreCompile.dir/all] 错误 2 make[1]: *** 正在等待未完成的任务.... Consolidate compiler generated dependencies of target glfw /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh.vert /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_directional_light_shadow.vert [ 3%] Built target json11 /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_point_light_shadow.vert /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_inefficient_pick.vert [ 5%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_vert.h [ 6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_point_light_shadow_vert.h [ 6%] Built target tinyobjloader [ 6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_directional_light_shadow_vert.h [ 6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_inefficient_pick_vert.h [ 7%] Built target glm_static [ 26%] Built target PilotShaderCompile [ 38%] Built target glfw [ 43%] Built target spdlog make: *** [Makefile:136：all] 错误 2 windys-dde@windys-dde-PC:/media/windys-dde/DATA/WorkSpaceDemo/Pilot$
> 
> 是因为系统的c库版本低了吗，当前系统搜索不到更高版本的c库了 deepin 20.5

`/media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/meta_parser: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/libclang.so.12`

**Comment by windyslove** [comment]
> > windys-dde@windys-dde-PC:/media/windys-dde/DATA/WorkSpaceDemo/Pilot$ ./build_linux.sh debug -- Using X11 for window creation -- Build spdlog: 1.9.2 -- Build type: Debug -- Configuring done -- Generating done -- Build files have been written to: /media/windys-dde/DATA/WorkSpaceDemo/Pilot/build Consolidate compiler generated dependencies of target tinyobjloader Consolidate compiler generated dependencies of target glm_static Consolidate compiler generated dependencies of target json11
> > **** [Precompile] BEGIN
> > [ 0%] Built target stb Consolidate compiler generated dependencies of target spdlog [ 1%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh.vert.spv [ 2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_directional_light_shadow.vert.spv [ 2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_inefficient_pick.vert.spv [ 2%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/spv/mesh_point_light_shadow.vert.spv /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/meta_parser: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/libclang.so.12) make[2]: *** [CMakeFiles/PilotPreCompile.dir/build.make:73：CMakeFiles/PilotPreCompile] 错误 1 make[1]: *** [CMakeFiles/Makefile2:261：CMakeFiles/PilotPreCompile.dir/all] 错误 2 make[1]: *** 正在等待未完成的任务.... Consolidate compiler generated dependencies of target glfw /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh.vert /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_directional_light_shadow.vert [ 3%] Built target json11 /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_point_light_shadow.vert /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/glsl/mesh_inefficient_pick.vert [ 5%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_vert.h [ 6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_point_light_shadow_vert.h [ 6%] Built target tinyobjloader [ 6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_directional_light_shadow_vert.h [ 6%] Generating /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/shader/generated/cpp/mesh_inefficient_pick_vert.h [ 7%] Built target glm_static [ 26%] Built target PilotShaderCompile [ 38%] Built target glfw [ 43%] Built target spdlog make: *** [Makefile:136：all] 错误 2 windys-dde@windys-dde-PC:/media/windys-dde/DATA/WorkSpaceDemo/Pilot$
> > 是因为系统的c库版本低了吗，当前系统搜索不到更高版本的c库了 deepin 20.5
> 
> ```
> /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/meta_parser: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /media/windys-dde/DATA/WorkSpaceDemo/Pilot/engine/bin/Linux/libclang.so.12
> ```
> 
> Only Ubuntu is official supported. @windyslove

好的谢谢你

**Comment by windyslove** [comment]
今天更新后编译通过了，但是运行报错
<details>
<summary>Log </summary>
/media/windys-dde/DATA/WorkSpace_DDE/Pilot/build/engine/source/editor/PilotEditor
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
</details>

**Comment by windyslove** [comment]
编译了个glibc2.29，在meta_parser那个目录 libm.so.6软链接到了libm-2.29.so后编译通过了，运行报错
<details>
<summary>log</summary>
/media/windys-dde/DATA/WorkSpace_DDE/Pilot/build/engine/source/editor/PilotEditor
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
</details>
