### ISSUE TITLE
components details里的参数无法通过拖动或者修改字符进行修改

### ISSUE THREAD

**Issue by PeterJohn** [BoomingTech/Pilot#76]
直接拖GO的坐标轴是可以的，但在components details里拖或者改都不行，并且拖了放手之后会丢失GO的选中状态。

**Comment by hyv1001** [comment]
@Ol6rin please check this issue

**Comment by zackszhu** [comment]
Adding a gif for illustration:
![Components Detail Bug](https://user-images.githubusercontent.com/7601610/162369405-ada872de-6a38-414f-a035-59c92507e10d.gif)

**Comment by Ol6rin** [comment]
感谢反馈！已经查明原因是为了平滑动画加的Transform帧buffer导致的，正在修复，会在下一次更新时发出。
