### ISSUE TITLE
windows平台build sln报错

### ISSUE THREAD

**Issue by transong** [BoomingTech/Pilot#8]
![image](https://user-images.githubusercontent.com/1109122/161572531-b2e4db84-0a98-4141-acfa-8575fc5f2646.png)

使用的vs2022

**Comment by hyv1001** [comment]
可以描述一下构建过程以及相关环境吗？比如windows 版本，windows sdk和visual studio的具体版本

**Comment by xgfeng** [comment]
你报的2个编译问题中第一个“error LNK2005: "public: static class Pilot::Vector3 const Pilot::PCamera::X" (?X@PCamera@Pilot@@2VVector3@2@B) 已经在 axis.obj 中定义”我在用VS2017编译也遇到了，解决方法就是添加链接参数"/FORCE:MULTIPLE"，具体修改可参考
https://github.com/xgfeng/Pilot/commit/ab9e1fbf7b4cd379672921c8fa6e971623681724
中engine/CMakeLists.txt的改动

**Comment by transong** [comment]
“error LNK2005: "public: static class Pilot::Vector3 const Pilot::PCamera::X"的问题解决了。vulkan库缺失那个还是没搞定，已经装上微信群的vulkanRT-1.3.204.1了

**Comment by transong** [comment]
版本	Windows 10 家庭中文版
版本号	21H2
安装日期	‎2021/‎5/‎3
操作系统内部版本	19044.1586
体验	Windows Feature Experience Pack 120.2212.4170.0

**Comment by transong** [comment]
cmake -S engine/ -B build -A x64
强制cmake设置x64平台解决了vulkan库缺失问题

**Comment by hyv1001** [comment]
This issue will be closed, please reopen or create a new ticket if you have any problems.
