### ISSUE TITLE
VS2022 CMake编译失败 Failed to run MSBuild command

### ISSUE THREAD

**Issue by Alobal** [BoomingTech/Pilot#82]
环境： win10，VS2022，CMake3.21
运行build脚本编译失败
```
PS D:\program\Pilot> .\build_windows.bat
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    鐢ㄤ簬 .NET Framework 鐨?
```

请问如何解决呢？

**Comment by hyv1001** [comment]
Have you built the project before?
It may be caused by the CMake cache or the missing path of MSBuild.exe.
Could you try to delete the build directory and run the build_windows.bat again?
Maybe this [stackflow link](https://stackoverflow.com/questions/44478492/cmake-failed-to-run-msbuild-command-msbuild-exe) can help.

**Comment by Alobal** [comment]
I have tried to delete cache and build again, it still doesn't work neither using cmd or CMake GUI.

![image](https://user-images.githubusercontent.com/35487993/162415936-d24d3622-97cf-4bfe-a9cb-25f2b63c1c61.png)

Yep, the simple solution is install an additional MSBuild of VS2019. I will choose this way if there is no solution for VS2022 only.
Thank you for your help!

**Comment by hyv1001** [comment]
This issue will be closed, please reopen or create a new ticket if still exists.

**Comment by Alobal** [comment]
I find it's the error of CMake 3.21, although 3.21 declared support for VS2022, it runs failed.  **CMake 3.23 is ok totally.**
