### ISSUE TITLE
spelling mistake: field -> filed

### ISSUE THREAD

**Issue by weiyi-boynextdoor** [BoomingTech/Pilot#87]
typedef std::tuple<setFuncion, getFuncion, getNameFuncion, getNameFuncion, getNameFuncion, getBoolFunc>
        filed_function_tuple;
    typedef std::tuple<getBaseClassReflectionInstanceListFunc, constructorWithPJson, writePJsonByName>
                                                                                                class_function_tuple;
    typedef std::tuple<setArrayFunc, getArrayFunc, getSizeFunc, getNameFuncion, getNameFuncion> array_function_tuple;

**Comment by hyv1001** [comment]
It's a known issue, will be fixed soon

**Comment by hyv1001** [comment]
Fixed by #183
