### ISSUE TITLE
About two-way map data structure

### ISSUE THREAD

**Issue by Altair-Alpha** [BoomingTech/Pilot#91]
**Is your feature request related to a problem? Please describe.**
When reading the scene management source code, I found that there's a lot use of two `unordered_map`s to represent a 1-to-1 relationship between guids and objects, like: 

https://github.com/BoomingTech/Pilot/blob/e5d43bcaa30a260251567e74feadb895786849aa/engine/source/runtime/function/scene/scene_allocator.h#L86-L88
https://github.com/BoomingTech/Pilot/blob/e5d43bcaa30a260251567e74feadb895786849aa/engine/source/runtime/function/scene/scene_manager.h#L58-L71

**Describe the solution you'd like**
Maybe it's better to implement a bidirectional map data structure(e.g. boost library has a `bimap` class) to replace this. Or at least I think we could change the value type of the map from `T` to `T*` to avoid doubled storing cost.

Please let me know if it is ok to make a PR on this.

**Comment by Ol6rin** [comment]
Thank you very much for helping us enhance Pilot engine!
It's right that there is no need to maintain 1-to-1 relationships with two maps.
We usually do this by putting structures in a buffer, one map from id(could be a number or a string) to the index in the buffer, 
then record id with the structure itself.
We've been working on the refactoring of SceneManager, updates will be released in the future.
