### ISSUE TITLE
Bug Report 'Game Mode' or 'Editor Mode' button in UI doesn't show completely

### ISSUE THREAD

**Issue by CRAFTSTARCN** [BoomingTech/Pilot#92]
**Describe the bug | Bug描述**
Latest version ([e5d43bc](https://github.com/BoomingTech/Pilot/commit/e5d43bcaa30a260251567e74feadb895786849aa)
Incomplete presentation of 'Game Mode' or 'Editor Mode' Button

**Steps to reproduce | 如何复现**
1. Just open the Pilot Engine

**Expected behavior | 预期行为**
It shall show the complete text.

**Screenshots/Logs | 截图/日志**
![ErrorButton](https://user-images.githubusercontent.com/24621848/162575012-ef883a1d-0940-4fb8-a4c9-498d8aefabb2.png)

**Desktop | 桌面环境**
 - OS: Windows 
 - Version: 10
 - CPU: 15-9400H
 - GPU: NVIDIA GeForce GTX 1660Ti
 - Memory: 16GB
 - Compiler: MSVC2019
 - Screen resolution: 1920x1080

**Comment by iaomw** [comment]
What is your resolution scale at 1080p? 
Is that 100% or something like 150%?

**Comment by CRAFTSTARCN** [comment]
> What is your resolution scale at 1080p? Is that 100% or something like 150%?

it's 125%, recommand by windows for my laptop, I think I shall use 100% instead of 125%, thanks.

**Comment by hyv1001** [comment]
Should be fixed by #118, plz reopen if still exists
