### ISSUE TITLE
PilotEditor.exe runtime error on launch: vkEnumeratePhysicalDevices reported zero accessible devices

### ISSUE THREAD

**Issue by goodgoodstudy2021** [BoomingTech/Pilot#97]
**Describe the bug | Bug描述**
编译成功之后，exe文件无法打开，windows日志为：
日志名称:          Application
来源:            Application Error
日期:            2022-04-10 16:35:44
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           LAPTOP-CVGTKPCF
描述:
错误应用程序名称: PilotEditor.exe，版本: 0.0.0.0，时间戳: 0x624e557f
错误模块名称: ucrtbase.dll，版本: 10.0.19041.789，时间戳: 0x2bd748bf
异常代码: 0xc0000409
错误偏移量: 0x000000000007286e
错误进程 ID: 0x4794
错误应用程序启动时间: 0x01d84cb5f6c9dc0d
错误应用程序路径: C:\Users\凡\Desktop\Pilot\Pilot\bin\PilotEditor.exe
错误模块路径: C:\windows\System32\ucrtbase.dll
报告 ID: 9d74d40d-b419-41f3-ad14-ac0c06381b48
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-04-10T08:35:44.9645455Z" />
    <EventRecordID>85945</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-CVGTKPCF</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PilotEditor.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>624e557f</Data>
    <Data>ucrtbase.dll</Data>
    <Data>10.0.19041.789</Data>
    <Data>2bd748bf</Data>
    <Data>c0000409</Data>
    <Data>000000000007286e</Data>
    <Data>4794</Data>
    <Data>01d84cb5f6c9dc0d</Data>
    <Data>C:\Users\凡\Desktop\Pilot\Pilot\bin\PilotEditor.exe</Data>
    <Data>C:\windows\System32\ucrtbase.dll</Data>
    <Data>9d74d40d-b419-41f3-ad14-ac0c06381b48</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Steps to reproduce | 如何复现**
1. 
2. 
3. 
4. 
5. 

**Expected behavior | 预期行为**
    
**Actual behavior | 实际行为**
A clear and concise description of what actually happened.

**Screenshots/Logs | 截图/日志**
If applicable, add screenshots and/or a video to help explain your problem.

**Desktop | 桌面环境**
 - OS: [ Windows,]
 - Version [Win10,]
 - CPU [AMD Ryzen 7 4800H with Radeon Graphics ]
 - GPU [ NVidia GeoForce GTX 1650 Ti]
 - Memory [16GB]
 - Compiler [VS2019]

**Additional context | 补充信息**

**Comment by hyv1001** [comment]
1. 能否在非中文路径下尝试编译运行
2. 是Debug版本还是Release版本，如果是Debug版本，最好可以给出Callstack

**Comment by goodgoodstudy2021** [comment]
无法在中文路径下编译，是Release版本的

**Comment by goodgoodstudy2021** [comment]
![image](https://user-images.githubusercontent.com/80575152/162618543-6d20824f-5ecf-4543-8e3e-c88c4e14085f.png)

**Comment by goodgoodstudy2021** [comment]
这是debug之后的结果

**Comment by hyv1001** [comment]
> ![image](https://user-images.githubusercontent.com/80575152/162618543-6d20824f-5ecf-4543-8e3e-c88c4e14085f.png)

如果是用vs2019或vs2022编译的话，需要设置PilotEditor这个项目为启动项目
![image](https://user-images.githubusercontent.com/102242553/162619298-00d0df81-88cd-4dbf-a30a-ce8ff0f18f8c.png)

**Comment by goodgoodstudy2021** [comment]
![image](https://user-images.githubusercontent.com/80575152/162619447-42cdaee3-f715-4d13-9328-aa8db0ac99f3.png)

设置PilotEditor为启动项后的结果

**Comment by hyv1001** [comment]
看上去是由于Vulkan无法找到GPU，可能是显卡驱动的原因，建议尝试以下操作：
1. 升级显卡驱动到最新版本，然后再尝试编译运行；
2. 如果1不起作用的话，下载安装[VulkanSDK:](https://vulkan.lunarg.com/sdk/home#windows) ,运行安装路径下Bin目录的vkcube.exe 以及 vulkaninfoSDK.exe，看一下运行结果

**Comment by goodgoodstudy2021** [comment]
![image](https://user-images.githubusercontent.com/80575152/162620132-d9e1d7e6-c3e6-4502-af37-25c4ba72a0b8.png)
![image](https://user-images.githubusercontent.com/80575152/162620158-c4d5e4a2-f6cf-42e7-849c-b7fe54b86d0c.png)

**Comment by goodgoodstudy2021** [comment]
显卡驱动是最新的，运行vulkan下边的两个exe后分别出现以上结果，vulkan只截取了最后那个模块的数据

**Comment by hyv1001** [comment]
你是不是还有一块AMD的集成显卡，这个显卡有没有更新？
可以参考这里面的方法：
https://github.com/godotengine/godot/issues/45104#issuecomment-857516908
https://github.com/godotengine/godot/issues/45104#issuecomment-961135736

**Comment by goodgoodstudy2021** [comment]
是的，好的，我去试试，十分感谢

**Comment by goodgoodstudy2021** [comment]
AMD显卡驱动是最新的
![image](https://user-images.githubusercontent.com/80575152/162623926-5a36b73d-dfed-4451-a2f8-f20b132f5ec8.png)

**Comment by goodgoodstudy2021** [comment]
![image](https://user-images.githubusercontent.com/80575152/162624069-30e3d2ff-a2e2-47d8-a3b9-058382598d95.png)

**Comment by hyv1001** [comment]
有尝试过[这个](https://github.com/godotengine/godot/issues/45104#issuecomment-857516908)解决方案吗

**Comment by goodgoodstudy2021** [comment]
![image](https://user-images.githubusercontent.com/80575152/162625513-03d6c570-67ec-4084-8bbe-15eee4242cbf.png)
成功了！这个是使用AMD显卡进行图形处理了嘛

**Comment by hyv1001** [comment]
> ![image](https://user-images.githubusercontent.com/80575152/162625513-03d6c570-67ec-4084-8bbe-15eee4242cbf.png) 成功了！这个是使用AMD显卡进行图形处理了嘛

这个问题应该是这种型号的AMD显卡导致的
默认引擎会选择独显而不是集显，所以大概率是N卡
但如果要确认的话最好还是debug跟踪一下，因为不确定有没有把两个显卡都识别出来

**Comment by goodgoodstudy2021** [comment]
好的，谢谢

**Comment by hyv1001** [comment]
This issue will be closed, please reopen or create a new ticket if still exists.
